name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # * Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.1

  service_easy_localization:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
