name: service_easy_localization
description: "TODO"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # * Data
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # * Conversion
  yaml: any

  # * Localization
  easy_logger: ^0.0.2
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  flutter_localized_locales: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
